### ISSUE TITLE
Avoyaka [avu] exemplar characters issues

### ISSUE THREAD

**Issue by moyogo** [silnrsi/sldr#29]
sldr/a/avu_Latn_SD.xml and sldr/a/avu_Latn_SD.xml have `{ı̣}` in the main exemplar characters.
It should be `ị` as listed in [Eileen Kilpatrick, "Orthographies of Moru-Maʼdi languages", *Occasional Papers in the Study of Sudanese Languages* No. 9](https://www.sil.org/resources/archives/35968), p. 88 or Rhonda Hartell, *Alphabets of Africa*, 1993.
The Avoyaka orthography seems to always indicate tone (with acute, circumflex, tilde) and `ị` and `{ı̣}` are visually identical with accents, which may be the cause of the issue.

**Comment by emily-roth** [comment]
Thank you so much for raising this issue! 

Your guess as to the source of the issue was correct: In several fonts (sometimes depending on if they are using subsetting or not),`{ị}` will keep its upper dot even when diacritics are added, which obviously was not intended. In the Bible Translation published in 2002 ([Tã-drı̣̃ Lẽlẽ Óꞌdí Óvârí Kâ](https://www.bible.com/bible/1766/MAT.1)), they got around the issue by using `{ı̣}` to make sure the upper dot didn't interfere with the diacritics. Clever solution, but still incorrect for the purposes of the SLDR, and most likely the source of the original incorrect data. 

I updated the file in the SLDR accordingly and it should be reflected in the master branch of the repo at this point. It'll update everywhere else when we do our next release of the SLDR, which should hopefully be sometime this coming November/December. Thank you again!
