### ISSUE TITLE
Tagbanwa: tbk.xml says the script is Tagb, but the exemplar characters are Latin?

### ISSUE THREAD

**Issue by madig** [silnrsi/sldr#39]
Hi there,
I noticed that https://github.com/silnrsi/sldr/blob/master/sldr/t/tbk.xml seems to identify the entry as `Tagb`, but the exemplar characters are all Latin. https://github.com/silnrsi/sldr/blob/master/sldr/t/tbk_Latn.xml identifies correctly as Latin. Is this intentional? 🤔

**Comment by madig** [comment]
The same issue seems to exist in https://github.com/silnrsi/sldr/blob/master/sldr/h/ha_NE.xml, the header says Arab but the exemplar glyphs are Latin.

**Comment by emily-roth** [comment]
If I had to guess, what most likely happened is that tbk.xml got generated with the information from tbk_Latn, but got mislabeled. A program was later run to make sure that the scripts were listed in the file data, and since the langtag tbk is tied to tbk_Tagb, it got labeled as such without changing the exemplar data. This isn't the first case of such an issue I've found and writing a test to detect more such instances is on my to-do list. In the meantime, thank you for bringing it to my attention manually!  

As for ha_NE, that might need looking into further. I'm going to consult with a few people and come back to that shortly. Thank you again for bringing it up!

**Comment by emily-roth** [comment]
Alright, we've taken a look and it indeed seems like ha_NE was originally labeled as Arab in Langtags before CLDR data came in and cemented that tag as Latn. We've fixed everything in SLDR and Langtags accordingly. Thank you again for bringing this to our attention!
